version: 2
project_name: sub2clash
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ldflags:
      - -s -w -X github.com/bestnite/sub2clash/constant.Version={{ .Version }}
    flags:
      - -trimpath
    hooks:
      pre:
        - cmd: npm install
          dir: server/frontend
        - cmd: VITE_APP_VERSION={{ .Version }} npm run build
          dir: server/frontend
archives:
  - formats: ["tar.gz"]
    format_overrides:
      - formats: ["zip"]
        goos: windows
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - templates
release:
  draft: true
upx:
  - enabled: true
    compress: best
nfpms:
  - id: sub2clash
    homepage: https://github.com/bestnite/sub2clash
    maintainer: Nite <admin@nite07.com>
    license: "MIT"
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    provides:
      - sub2clash
